version: "2"
services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.codeship
    environment:
      - APP_ENV=test
  production:
    build: .
    environment:
      - APP_ENV=production
    volumes:
      - /home/simon/.netrc:/root/.netrc
