version: "2"
services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.codeship
    cached: true
    environment:
      - APP_ENV=test
  production:
    build: .
    environment:
      - APP_ENV=production
      
